import type { Metadata } from "next";
import "./globals.css";
import Skills from "./components/Home/Skills/Skills";

export const metadata: Metadata = {
  title: "Taha Paracha",
  description: "Generated by create next app",
};

export default function RootLayout(
  { children } : 
  {
  children: React.ReactNode, 
  }) {
  return (
    <html lang="en">
      <body>

          {children}

      </body>
    </html>
  );
}
